Repository Artificial-Intelligence-HSBI-TDU/KI-Vorlesung, pull requests merged in 2022-10, with the labels that each got.

#184 [ORGA] Link auf Moodle-Kursraum einpflegen
  markdown/_index.md
Labels: bug

#186 [ORGA] Hinweise zur Gruppen und Beitritt zu Breakout-Gruppen
  data/schedule.yaml
  markdown/_index.md
  markdown/org/faq.md
Labels: bug, überarbeiten, vorlesungen

#188 [FAQ] Fix how to review
  markdown/org/faq.md
  markdown/org/images/howtofeedback1.png
  markdown/org/images/howtofeedback2.png
  markdown/org/images/howtofeedback3.png
  markdown/org/images/howtofeedback4.png
  markdown/org/images/howtofeedback5.png
Labels: documentation, aufgaben

#191 [ASSIGNMENT] Aufgaben für Meilenstein 1.1
  markdown/assignments/sheet01.md
Labels: aufgaben

#194 [ASSIGNMENT] Aufgaben für Meilenstein 1.2
  markdown/assignments/sheet02.md
Labels: aufgaben

#192 [ASSIGNMENT] Aufgaben für Meilenstein 1.3
  markdown/assignments/sheet03.md
Labels: aufgaben

#193 [ASSIGNMENT] Aufgaben für Meilenstein 1.4
  markdown/assignments/sheet04.md
Labels: aufgaben
