Repository Artificial-Intelligence-HSBI-TDU/KI-Vorlesung, pull requests merged in 2022-11, with the labels that each got.

#199 [VL] DTL: add Gini Impurity and CART (as outlook + blogs)
  markdown/dtl/entropy.md
  markdown/dtl/id3.md
Labels: enhancement, vorlesungen

#200 [VL] fix the mapping of lessons and assignments
  markdown/csp/ac3.md
  markdown/csp/backtrackingsearch.md
  markdown/csp/heuristics.md
  markdown/csp/intro.md
  markdown/dtl/cal2.md
  markdown/dtl/cal3.md
  markdown/dtl/entropy.md
  markdown/dtl/id3.md
  markdown/dtl/mlbasics.md
  markdown/dtl/pruning.md
  markdown/games/alphabeta.md
  markdown/games/heuristics.md
  markdown/games/intro.md
  markdown/games/minimax.md
Labels: bug, vorlesungen

#201 [FAQ] Review: write some text if all checkboxes 'false'
  markdown/org/faq.md
Labels: enhancement, vorlesungen

#202 [FAQ] Upload multiple files
  markdown/org/faq.md
  markdown/org/images/ilias_upload.png
Labels: enhancement, vorlesungen

#195 [ASSIGNMENT] Aufgaben für Poster 1
  markdown/assignments/images/screenshot_stundenplan.png
  markdown/assignments/poster1.md
  markdown/org/faq.md
Labels: aufgaben

#206 [ASSIGNMENT] B01..B04, P1: add note regarding todo markers in AIMA-Python
  markdown/assignments/poster1.md
  markdown/assignments/sheet01.md
  markdown/assignments/sheet02.md
  markdown/assignments/sheet03.md
  markdown/assignments/sheet04.md
Labels: bug, aufgaben

#203 [ORG] Füge Info zu Unterstützung durch DigikoS ein
  markdown/_index.md
Labels: enhancement

#209 [ORG] Abbildung zu DigikoS funktioniert noch nicht im gerenderten Skript
  README.md
  markdown/_index.md
Labels: bug, vorlesungen

#210 [ASSIGNMENT] Poster 1: Fußnoten und Links interferieren
  markdown/assignments/poster1.md
Labels: bug, aufgaben

#211 [ORG] add url to Digital Mobil project
  README.md
  markdown/_index.md
Labels: bug, vorlesungen

#212 Meilenstein 2.1 - Perzeptron
  markdown/assignments/files/perzeptron_lernalgorithmus_starter.ipynb
  markdown/assignments/sheet05.md
Labels: aufgaben

#214 Zusätzliche Bemerkungen zu der Nachfrist im faq
  markdown/org/faq.md
Labels: bug, aufgaben, vorlesungen

#215 Milestone 2.2 and starter code
  markdown/assignments/files/Logistische_Regression_Starter.ipynb
  markdown/assignments/files/logistische_regression_starter.ipynb
  markdown/assignments/sheet06.md
Labels: aufgaben

#216 [ASSIGNMENTS] Fix IPYNB: add space after '##', remove space after '$$'
  markdown/assignments/files/logistische_regression_starter.ipynb
Labels: bug, aufgaben

#217 [ASSIGNMENTS] Sheet06 / M2.2: fix some typos
  markdown/assignments/files/logistische_regression_starter.ipynb
Labels: bug, aufgaben
