Repository Artificial-Intelligence-HSBI-TDU/KI-Vorlesung, pull requests merged in 2023-09, with the labels that each got.

#270 Orga: remove edit-url from hugo-conf
  hugo_conf.yaml
Labels: bug

#271 Tool: replace tabs/tab shortcode with tabs/tab fenced div
  readme.md
Labels: tooling

#272 Update graphic schedule
  admin/images/ki_fahrplan_2023-2024.png
  homework/sheet01.md
  homework/sheet02.md
  homework/sheet03.md
  homework/sheet04.md
  homework/sheet05.md
  homework/sheet06.md
  homework/sheet07.md
  homework/sheet08.md
  homework/sheet09.md
  homework/sheet10.md
  homework/sheet11.md
  homework/sheet12.md
  readme.md
Labels: vorlesungen

#273 actions/checkout: bump version to v4
  .github/workflows/hugo.yaml
  .github/workflows/slides.yaml
  .github/workflows/tests.yaml
Labels: tooling

#274 Org: revise assignment of homework sheets to lectures/sessions
  lecture/csp/ac3.md
  lecture/csp/backtrackingsearch.md
  lecture/csp/heuristics-csp.md
  lecture/csp/intro-csp.md
  lecture/dtl/cal2.md
  lecture/dtl/cal3.md
  lecture/dtl/entropy.md
  lecture/dtl/id3.md
  lecture/dtl/mlbasics.md
  lecture/dtl/pruning.md
  lecture/games/alphabeta.md
  lecture/games/heuristics-minimax.md
  lecture/games/intro-games.md
  lecture/games/minimax.md
  lecture/logic/intro-logic.md
  lecture/logic/modelle.md
  lecture/logic/resolution.md
  lecture/logic/syntax.md
  lecture/naivebayes/nb.md
  lecture/naivebayes/probability.md
  lecture/nn/nn1_perceptron.md
  lecture/nn/nn2_linear_regression.md
  lecture/nn/nn3_logistic_regression.md
  lecture/nn/nn4_overfitting.md
  lecture/nn/nn5_mlp.md
  lecture/nn/nn6_backprop.md
  lecture/nn/nn7_training_testing.md
Labels: bug, aufgaben, vorlesungen

#275 Lectures: remove extra centering of images (images are self centered)
  homework/sheet01.md
  lecture/csp/ac3.md
  lecture/csp/backtrackingsearch.md
  lecture/csp/heuristics-csp.md
  lecture/csp/intro-csp.md
  lecture/dtl/cal2.md
  lecture/dtl/mlbasics.md
  lecture/ea/ga.md
  lecture/ea/intro-ea.md
  lecture/games/heuristics-minimax.md
  lecture/games/intro-games.md
  lecture/games/minimax.md
  lecture/intro/intro-ai.md
  lecture/intro/problems.md
  lecture/search/local/annealing.md
  lecture/search/local/gradient.md
Labels: bug, vorlesungen

#276 [Orga] replace Moodle link with link to Google classroom
  readme.md
Labels: bug, vorlesungen

#277 Orga: organisiere Übungsblätter für NN-Teil
  homework/sheet07.md
  homework/sheet08.md
  homework/sheet09.md
  homework/sheet10.md
  homework/sheet11.md
  homework/sheet12.md
  readme.md
Labels: aufgaben

#280 Orga: update grading HSBI
  readme.md
Labels: w23, prüfungen, hsbi

#281 Lecture: add nn-challenges
  lecture/nn/files/Feature_Scaling_Starter.ipynb
  lecture/nn/images/contour_plot_a.png
  lecture/nn/images/contour_plot_b.png
  lecture/nn/nn2_linear_regression.md
  lecture/nn/nn5_mlp.md
Labels: vorlesungen, w23, tdu

#282 Lecture: replace link to ipynb
  lecture/nn/nn2_linear_regression.md
Labels: bug, vorlesungen, w23, tdu

#278 Homework: rework Naive Bayes assignment
  homework/sheet06.md
Labels: aufgaben, high prio

#283 Tool: add dependabot
  .github/dependabot.yml
Labels: tooling

#284 Orga: fix dates in overview tables
  readme.md
Labels: bug, vorlesungen, w23, tdu, hsbi

#285 Orga: improve title shown as tab title
  readme.md
Labels: vorlesungen

#286 Orga: fix markdownlint warnings
  readme.md
Labels: vorlesungen

#288 Orga: replace outdated note with link to faq
  readme.md
Labels: vorlesungen, w23, tdu

#289 Orga: remove unnecessary notice of start time tdu (09.10.23)
  readme.md
Labels: bug, vorlesungen, w23, tdu

#290 Orga: use shorter title in tables
  readme.md
Labels: vorlesungen, w23, tdu, hsbi

#291 Homework: fix numbering for sheet 01
  homework/sheet01.md
Labels: bug, aufgaben

#292 Homework: improve formatting in sheet 05
  homework/sheet05.md
Labels: bug, aufgaben

#295 Homework: fix math rendering in sheet 09
  homework/sheet09.md
Labels: bug, aufgaben

#296 Homework: fix math rendering in sheet 10
  homework/sheet10.md
Labels: bug, aufgaben

#300 Orga: fix double title
  readme.md
Labels: bug, vorlesungen

#302 Orga: add deadlines (HSBI)
  readme.md
Labels: aufgaben, w23, hsbi

#303 Orga: remove year to improve readability (HSBI)
  readme.md
Labels: vorlesungen, w23, hsbi

#304 Orga: add link to demo-exam (HSBI)
  admin/exams-hsbi.md
Labels: w23, prüfungen, hsbi

#305 Grading HSBI: use tabs in exams page
  admin/exams-hsbi.md
Labels: w23, prüfungen, hsbi

#306 Hugo: use 'external link' as icon for FAQ shortcut
  hugo_conf.yaml
Labels: vorlesungen, w23

#308 Orga: add ue deadlines (TDU)
  readme.md
Labels: w23, tdu

#307 Grading TDU
  admin/exams-tdu.md
  readme.md
Labels: w23, prüfungen, tdu
