Repository Artificial-Intelligence-HSBI-TDU/KI-Vorlesung, pull requests merged in 2024-09, with the labels that each got.

#363 Fahrplan-Änderung
  admin/images/fahrplan.png
  readme.md
Labels: vorlesungen

#364 Homework: move intro task as bonus to perceptron homework
  homework/sheet-nn-perceptron.md
  homework/sheet-search.md
Labels: aufgaben

#372 Orga: fix lab time (TDU)
  readme.md
Labels: prüfungen, tdu
